-- Logements les plus occupés
SELECT 
    l.NUM_LOGEMENT,
    v.NOM_VILLE,
    tl.DESCRIPTION AS TYPE,
    COUNT(fp.NUM_RESIDENT) AS TOTAL_RESIDENTS_ACCUEILLIS,
    SUM(EXTRACT(DAY FROM (r.DATE_DEPART - r.DATE_ARRIVE))) AS TOTAL_JOURS_OCCUPES
FROM LOGEMENTS l
JOIN VILLES v ON l.NUM_VILLE = v.NUM_VILLE
JOIN TYPES_LOGEMENT tl ON l.CODE_TYPE = tl.CODE_TYPE
JOIN RESERVATIONS r ON l.NUM_LOGEMENT = r.NUM_LOGEMENT
LEFT JOIN FAIT_PARTI fp ON r.NUM_LOGEMENT = fp.NUM_LOGEMENT AND r.DATE_ARRIVE = fp.DATE_ARRIVE
GROUP BY l.NUM_LOGEMENT, v.NOM_VILLE, tl.DESCRIPTION
ORDER BY TOTAL_RESIDENTS_ACCUEILLIS DESC, TOTAL_JOURS_OCCUPES DESC;