SELECT 
    l.NUM_LOGEMENT,
    v.NOM_VILLE,
    tl.DESCRIPTION,
    COUNT(r.DATE_ARRIVE) AS NB_RESERVATIONS
FROM LOGEMENTS l
JOIN VILLES v ON l.NUM_VILLE = v.NUM_VILLE
JOIN TYPES_LOGEMENT tl ON l.CODE_TYPE = tl.CODE_TYPE
-- Jointure GAUCHE pour inclure même ceux qui n'ont aucune réservation
LEFT JOIN RESERVATIONS r ON l.NUM_LOGEMENT = r.NUM_LOGEMENT
GROUP BY l.NUM_LOGEMENT, v.NOM_VILLE, tl.DESCRIPTION
HAVING COUNT(r.DATE_ARRIVE) = 0 -- Jamais reservés
   OR COUNT(r.DATE_ARRIVE) < 2  -- Ou très peu réservés
ORDER BY NB_RESERVATIONS ASC;