-- Trouver les logements qui cumulent le plus de problèmes techniques (Maintenance) ET de problèmes humains (Conflits générés par leurs résidents).
SELECT 
    v.NOM_VILLE,
    l.NUM_LOGEMENT,
    tl.DESCRIPTION AS TYPE,
    COUNT(DISTINCT m.NUM_MAINTENANCE) AS NB_INTERVENTIONS_TECH,
    COUNT(DISTINCT c.NUM_CONFLIT) AS NB_CONFLITS_LIES,
    (COUNT(DISTINCT m.NUM_MAINTENANCE) + COUNT(DISTINCT c.NUM_CONFLIT)) AS INDICE_PROBLEME
FROM LOGEMENTS l
JOIN VILLES v ON l.NUM_VILLE = v.NUM_VILLE
JOIN TYPES_LOGEMENT tl ON l.CODE_TYPE = tl.CODE_TYPE
-- Jointure gauche pour la maintenance
LEFT JOIN MAINTENANCE m ON l.NUM_LOGEMENT = m.NUM_LOGEMENT
-- Jointure complexe pour lier le logement aux conflits via les résidents
LEFT JOIN FAIT_PARTI fp ON l.NUM_LOGEMENT = fp.NUM_LOGEMENT
LEFT JOIN PARTIS_CONFLIT pc ON fp.NUM_RESIDENT = pc.NUM_RESIDENT
LEFT JOIN CONFLIT c ON pc.NUM_CONFLIT = c.NUM_CONFLIT
GROUP BY v.NOM_VILLE, l.NUM_LOGEMENT, tl.DESCRIPTION
HAVING (COUNT(DISTINCT m.NUM_MAINTENANCE) + COUNT(DISTINCT c.NUM_CONFLIT)) > 0
ORDER BY INDICE_PROBLEME DESC;