SELECT 
    v.NOM_VILLE,
    COUNT(r.DATE_ARRIVE) AS NB_SEJOURS,
    -- Moyenne de la différence entre départ et arrivée
    ROUND(AVG(EXTRACT(DAY FROM (r.DATE_DEPART - r.DATE_ARRIVE))), 0) AS DUREE_MOYENNE_JOURS
FROM RESERVATIONS r
JOIN LOGEMENTS l ON r.NUM_LOGEMENT = l.NUM_LOGEMENT
JOIN VILLES v ON l.NUM_VILLE = v.NUM_VILLE
GROUP BY v.NOM_VILLE
ORDER BY DUREE_MOYENNE_JOURS DESC;