--- Permet de connaitre les taux de remplissage des activités

SELECT 
    a.JOUR_SEMAINE,
    COUNT(p.NUM_RESIDENT) AS TOTAL_PARTICIPANTS,
    COUNT(DISTINCT a.NUM_ACTIVITE) AS NB_ACTIVITES_PROPOSEES,
    ROUND(CAST(COUNT(p.NUM_RESIDENT) AS DECIMAL) / NULLIF(COUNT(DISTINCT a.NUM_ACTIVITE), 0), 2) AS DENSITE_PARTICIPATION
FROM ACTIVITEES a
LEFT JOIN PARTICIPE p ON a.NUM_ACTIVITE = p.NUM_ACTIVITE
GROUP BY a.JOUR_SEMAINE
ORDER BY TOTAL_PARTICIPANTS DESC;