-- Activité la plus populaire par type de logement
SELECT 
    tl.DESCRIPTION AS TYPE_LOGEMENT,
    ta.NOM_TYPE_ACTIVITE,
    COUNT(p.NUM_RESIDENT) AS NB_PARTICIPANTS
FROM PARTICIPE p
JOIN ACTIVITEES a ON p.NUM_ACTIVITE = a.NUM_ACTIVITE
JOIN TYPES_ACTIVITE ta ON a.TYPE_ACTIVITE = ta.TYPE_ACTIVITE
JOIN LOGEMENTS l ON a.NUM_LOGEMENT = l.NUM_LOGEMENT
JOIN TYPES_LOGEMENT tl ON l.CODE_TYPE = tl.CODE_TYPE
GROUP BY tl.DESCRIPTION, ta.NOM_TYPE_ACTIVITE
ORDER BY NB_PARTICIPANTS DESC;