CREATE TABLE TYPES_LOGEMENT(
   CODE_TYPE VARCHAR(50),
   DESCRIPTION VARCHAR(50),
   PRIMARY KEY(CODE_TYPE)
);

CREATE TABLE RESIDENTS(
   NUM_RESIDENT INT,
   NOM VARCHAR(50),
   PRENOM VARCHAR(50),
   PRIMARY KEY(NUM_RESIDENT)
);

CREATE TABLE TYPE_INTERVENTION(
   NUM_URGENCE INT,
   NOM VARCHAR(50),
   PRIMARY KEY(NUM_URGENCE)
);

CREATE TABLE VILLES(
   NUM_VILLE INT,
   NOM_VILLE VARCHAR(50),
   PRIMARY KEY(NUM_VILLE)
);

CREATE TABLE TYPES_ACTIVITE(
   TYPE_ACTIVITE INT,
   NOM_TYPE_ACTIVITE VARCHAR(50),
   PRIMARY KEY(TYPE_ACTIVITE)
);

CREATE TABLE CONFLIT(
   NUM_CONFLIT INT,
   DATE_CONFLIT DATE,
   DESCRIPTION VARCHAR(50),
   PRIMARY KEY(NUM_CONFLIT)
);

CREATE TABLE GROUPE(
   NUM_GROUPE INT,
   NOM VARCHAR(50),
   PRIMARY KEY(NUM_GROUPE)
);

CREATE TABLE LOGEMENTS(
   NUM_LOGEMENT INT,
   NOMBRE_CHAMBRES INT,
   EQUIPEMENT VARCHAR(50),
   PRIX_SEMAINE_SAIS_BASSE DECIMAL(15,2),
   PRIX_SEMAINE_SAIS_HAUTE DECIMAL(15,2),
   NUM_GROUPE INT,
   NUM_VILLE INT NOT NULL,
   CODE_TYPE VARCHAR(50) NOT NULL,
   PRIMARY KEY(NUM_LOGEMENT),
   FOREIGN KEY(NUM_GROUPE) REFERENCES GROUPE(NUM_GROUPE),
   FOREIGN KEY(NUM_VILLE) REFERENCES VILLES(NUM_VILLE),
   FOREIGN KEY(CODE_TYPE) REFERENCES TYPES_LOGEMENT(CODE_TYPE)
);

CREATE TABLE RESERVATIONS(
   NUM_LOGEMENT INT,
   DATE_ARRIVE TIMESTAMP,
   DATE_DEPART TIMESTAMP,
   PRIMARY KEY(NUM_LOGEMENT, DATE_ARRIVE),
   FOREIGN KEY(NUM_LOGEMENT) REFERENCES LOGEMENTS(NUM_LOGEMENT)
);

CREATE TABLE MAINTENANCE(
   NUM_MAINTENANCE INT,
   NIVEAU_URGENCE INT,
   DATE_PLANIFIEE DATE,
   NUM_URGENCE INT NOT NULL,
   NUM_LOGEMENT INT NOT NULL,
   PRIMARY KEY(NUM_MAINTENANCE),
   FOREIGN KEY(NUM_URGENCE) REFERENCES TYPE_INTERVENTION(NUM_URGENCE),
   FOREIGN KEY(NUM_LOGEMENT) REFERENCES LOGEMENTS(NUM_LOGEMENT)
);

CREATE TABLE ACTIVITEES(
   NUM_ACTIVITE INT,
   NOM_ACTIVITE VARCHAR(50),
   JOUR_SEMAINE VARCHAR(50),
   NUM_GROUPE INT,
   TYPE_ACTIVITE INT NOT NULL,
   NUM_LOGEMENT INT,
   PRIMARY KEY(NUM_ACTIVITE),
   FOREIGN KEY(NUM_GROUPE) REFERENCES GROUPE(NUM_GROUPE),
   FOREIGN KEY(TYPE_ACTIVITE) REFERENCES TYPES_ACTIVITE(TYPE_ACTIVITE),
   FOREIGN KEY(NUM_LOGEMENT) REFERENCES LOGEMENTS(NUM_LOGEMENT)
);

CREATE TABLE FAIT_PARTI(
   NUM_LOGEMENT INT,
   DATE_ARRIVE TIMESTAMP,
   NUM_RESIDENT INT,
   PRIMARY KEY(NUM_LOGEMENT, DATE_ARRIVE, NUM_RESIDENT),
   FOREIGN KEY(NUM_LOGEMENT, DATE_ARRIVE) REFERENCES RESERVATIONS(NUM_LOGEMENT, DATE_ARRIVE),
   FOREIGN KEY(NUM_RESIDENT) REFERENCES RESIDENTS(NUM_RESIDENT)
);

CREATE TABLE PARTICIPE(
   NUM_RESIDENT INT,
   NUM_ACTIVITE INT,
   PRIMARY KEY(NUM_RESIDENT, NUM_ACTIVITE),
   FOREIGN KEY(NUM_RESIDENT) REFERENCES RESIDENTS(NUM_RESIDENT),
   FOREIGN KEY(NUM_ACTIVITE) REFERENCES ACTIVITEES(NUM_ACTIVITE)
);

CREATE TABLE PARTIS_CONFLIT(
   NUM_RESIDENT INT,
   NUM_CONFLIT INT,
   PRIMARY KEY(NUM_RESIDENT, NUM_CONFLIT),
   FOREIGN KEY(NUM_RESIDENT) REFERENCES RESIDENTS(NUM_RESIDENT),
   FOREIGN KEY(NUM_CONFLIT) REFERENCES CONFLIT(NUM_CONFLIT)
);
